// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPNYfTi3q1r0JSR6UUyaSJIEBgyMUc1aw',
    appId: '1:636213838433:web:d3bd8c89deb97c13652020',
    messagingSenderId: '636213838433',
    projectId: 'medicare-admin-b7266',
    authDomain: 'medicare-admin-b7266.firebaseapp.com',
    storageBucket: 'medicare-admin-b7266.firebasestorage.app',
    measurementId: 'G-DX1C0564X1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDErQvpOk3UzkviJT68mrfg3CFCmDHoQb4',
    appId: '1:636213838433:android:a0fa967e78684e9d652020',
    messagingSenderId: '636213838433',
    projectId: 'medicare-admin-b7266',
    storageBucket: 'medicare-admin-b7266.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAa_e9JggcfPe4MErrga-2qZT5BZcO-kQ',
    appId: '1:636213838433:ios:0300f1817cf443c4652020',
    messagingSenderId: '636213838433',
    projectId: 'medicare-admin-b7266',
    storageBucket: 'medicare-admin-b7266.firebasestorage.app',
    iosBundleId: 'com.example.medicare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAa_e9JggcfPe4MErrga-2qZT5BZcO-kQ',
    appId: '1:636213838433:ios:0300f1817cf443c4652020',
    messagingSenderId: '636213838433',
    projectId: 'medicare-admin-b7266',
    storageBucket: 'medicare-admin-b7266.firebasestorage.app',
    iosBundleId: 'com.example.medicare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPNYfTi3q1r0JSR6UUyaSJIEBgyMUc1aw',
    appId: '1:636213838433:web:9506914511c319bc652020',
    messagingSenderId: '636213838433',
    projectId: 'medicare-admin-b7266',
    authDomain: 'medicare-admin-b7266.firebaseapp.com',
    storageBucket: 'medicare-admin-b7266.firebasestorage.app',
    measurementId: 'G-F61RD2FE1W',
  );
}
